### ISSUE TITLE
Does ESIGate support proxying to a server which requires a peer certificate?

### ISSUE THREAD

**Issue by annahosanna** [esigate/esigate#136]
Does ESIGate support proxying to a server which requires peer certificate negotiation?  For instance specifying a local keystore on the ESIGate server, and the certificate's keystore alias which ESIGate should use as its client certificate?

I already know that Tomcat can be configured to request a peer certificate for connections to the ESIGate proxy. 

Thank you

**Comment by fxbonnet** [comment]
This is not currently supported, but should not be too hard to implement.
HttpComponents-client supports it:
https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/conn/ssl/SSLSocketFactory.html
https://hc.apache.org/httpcomponents-client-ga/httpclient/examples/org/apache/http/examples/client/ClientCustomSSL.java

So basically you just have to customize a little the HttpClient used by ESIGate. In order to do that, you need to modify method org.esigate.http.HttpClientRequestExecutor.HttpClientRequestExecutorBuilder.buildHttpClient()

**Comment by fxbonnet** [comment]
Closing this issue. If someone wants to work on it, feel free to reopen.
