### ISSUE TITLE
FetchEvent#getHttpResponse().getStatusLine().getUri()  is not the same as  FetchEvent#getHttpRequest().getOriginal().getRequestLine().getUri()

### ISSUE THREAD

**Issue by nricheton** [esigate/esigate#23]
When preserveHost is true, I expect that FetchEvent#getHttpResponse().getStatusLine().getUri()  is the same as  FetchEvent#getHttpRequest().getOriginal().getRequestLine().getUri()

But the hostname is lost in getHttpResponse (a wrapping class from HttpClient) and you have to get the original request to retrieve the value.

**Comment by fxbonnet** [comment]
I don't understand. As far as I know there is no getUri() method in StatusLine class.

**Comment by fxbonnet** [comment]
Ok. I guess you were talking about FetchEvent#getHttpRequest().getRequestLine().getUri() and FetchEvent#getHttpRequest().getOriginal().getRequestLine().getUri()

**Comment by fxbonnet** [comment]
Ok. I guess you were talking about
   * FetchEvent#getHttpRequest().getRequestLine().getUri() 
and
   * FetchEvent#getHttpRequest().getOriginal().getRequestLine().getUri()

The problem comes from org.apache.http.impl.execchain.ProtocolExec.execute(HttpRoute, HttpRequestWrapper, HttpClientContext, HttpExecutionAware) who rewrites the URI to a relative URI by calling method org.apache.http.impl.execchain.ProtocolExec.rewriteRequestURI(HttpRequestWrapper, HttpRoute)
So the URI of the HttpRequestWrapper is relative even if the one from the original request is absolute.
I don't see how we could fix this.

**Comment by fxbonnet** [comment]
I am closing this enhancement request as it cannot be fixed
